title: Al Porter Music
permalink: /:title
description: Music for your entertaining needs
exclude: ["vendor", "CNAME", "Gemfile", "LICENSE", "README.md"]

google_analytics: XXXXXXXXX

social:
  twitter:
#    id:
  facebook:
#    id:
  spotify:
#    id:
  instagram:
    id: al_porter_music
