title: Al Porter Music
permalink: /:title
description: Music for your entertaining needs
exclude: ["vendor", "CNAME", "Gemfile", "LICENSE", "README.md"]
url: https://ashepherd.github.io/alan-porter-music
areaServed: ["Cape Cod"]
email: "alportermusic@gmail.com"
keywords: ["guitar", "acoustic music", "vocals", "musician", "weddings", "restaurant", "party", "live music"]
genre: ["Acoustic", "Singer/Songwriter", "Pop", "Rock"]

google_analytics: XXXXXXXXX

social:
  twitter:
#    id:
  facebook:
#    id:
  spotify:
#    id:
    playlist:
      id: 21u5uFFquSrvAZO52lVTbE
  instagram:
    id: al_porter_music
  venmo:
    id: Al-Porter-Music
