title: Al Porter Music
permalink: /:title
description: Music for your entertaining needs
exclude: ["vendor", "CNAME", "Gemfile", "LICENSE", "README.md"]
url: https://ashepherd.github.io/alan-porter-music/
google_analytics: XXXXXXXXX

social:
  twitter:
#    id:
  facebook:
#    id:
  spotify:
#    id:
    playlist:
      id: 21u5uFFquSrvAZO52lVTbE
  instagram:
    id: al_porter_music
  venmo:
    id: al-porter-music
